import {MigrationInterface, QueryRunner} from "typeorm";

export class Initial1660381347348 implements MigrationInterface {
    name = 'Initial1660381347348'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "area" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_39d5e4de490139d6535d75f42ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "region" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "areaId" integer, CONSTRAINT "PK_5f48ffc3af96bc486f5f3f3a6da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "regionId" integer, CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "solar_power_plant_owner" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "gender" character varying, "DOB" TIMESTAMP, "phoneNumber" character varying, "address" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_345f8216af43309afd71e3cfa58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "solar_power_plant" ("id" SERIAL NOT NULL, "officialId" character varying, "name" character varying NOT NULL DEFAULT '発電所名', "location" character varying, "totalPowerOutput" double precision, "classification" character varying, "lat" double precision, "lng" double precision, "linked" boolean, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "solarPowerPlantOwnerId" integer, "officialSolarPowerPlantOwnerId" integer, "cityId" integer, "regionId" integer, CONSTRAINT "PK_eb30772fdbc759c906ab24bcddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_applications" ("id" SERIAL NOT NULL, "jobId" integer NOT NULL, "solarPowerPlantMaintainerId" integer NOT NULL, "suggestedPrice" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c56a5e86707d0f0df18fa111280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transaction_status_enum" AS ENUM('PENDING', 'PROCCESSING', 'FAILED', 'SUCCESSFUL')`);
        await queryRunner.query(`CREATE TABLE "payment_transaction" ("id" SERIAL NOT NULL, "transactionId" character varying NOT NULL, "amount" integer NOT NULL, "status" "public"."payment_transaction_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "jobId" integer, CONSTRAINT "PK_82c3470854cf4642dfb0d7150cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_file_info" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "mimetype" character varying, "encoding" character varying, "storageLocation" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "jobId" integer, CONSTRAINT "PK_5788dbedb25f95279773c635c17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_status_enum" AS ENUM('DRAFT', 'REGISTERED', 'OPEN', 'TEMP_PAYMENT', 'WAITING_COMPLETION', 'ORDER_EREVALUATION', 'CONTRACTOR_EVALUATION', 'COMPLETED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "job" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "category" character varying NOT NULL, "shortDescription" character varying NOT NULL, "longDescription" character varying NOT NULL, "location" character varying NOT NULL, "applicationDeadline" TIMESTAMP NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "budget" integer NOT NULL, "status" "public"."job_status_enum" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "solarPowerPlantId" integer, "approvedApplicantId" integer, CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "favorite_jobs" ("id" SERIAL NOT NULL, "jobId" integer NOT NULL, "solarPowerPlantMaintainerId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_701db8746db1b62c2e1a84621d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "representative" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "gender" character varying, "DOB" TIMESTAMP, "phoneNumber" character varying, "address" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2abe568eacaba9eba605bb231bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "solar_power_plant_maintainer" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "intro" character varying, "phoneNumber" character varying, "address" character varying, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "representativeId" integer, CONSTRAINT "REL_a84328fcf8e3e5f5885d164116" UNIQUE ("representativeId"), CONSTRAINT "PK_be941f30b2345c101fd4496727b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_transaction_status_enum" AS ENUM('PENDING', 'PROCCESSING', 'FAILED', 'SUCCESSFUL')`);
        await queryRunner.query(`CREATE TABLE "user_transaction" ("id" SERIAL NOT NULL, "transactionId" character varying NOT NULL, "price" integer NOT NULL, "status" "public"."user_transaction_status_enum" NOT NULL DEFAULT 'PROCCESSING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_e36b77a5263ac0f191277c4c5d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_info" ("id" SERIAL NOT NULL, "filename" character varying, "mimetype" character varying, "encoding" character varying, "storageLocation" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_13933cc183be28374e28f2f8b87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" SERIAL NOT NULL, "content" character varying NOT NULL, "senderId" integer NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "channelId" integer, "uploadedFileId" integer, CONSTRAINT "REL_96d3ca090d4097b57746349736" UNIQUE ("uploadedFileId"), CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channel" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_590f33ee6ee7d76437acf362e39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channels_members" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "channelId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7c5619f79752a09f431bb7abeb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_usertype_enum" AS ENUM('UNREGISTERED', 'UNVERIFIED', 'PENDING_PROFILE', 'OWNER', 'MAINTAINER', 'OWNER_MAINTAINER', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."user_accounttype_enum" AS ENUM('FREE', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "userType" "public"."user_usertype_enum" NOT NULL DEFAULT 'UNVERIFIED', "accountType" "public"."user_accounttype_enum" NOT NULL DEFAULT 'FREE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "solarPowerPlantOwnerId" integer, "solarPowerPlantMaintainerId" integer, "hasverified" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_c4bfb1f8b58fe276fce02f1d55" UNIQUE ("solarPowerPlantOwnerId"), CONSTRAINT "REL_21c478baa4640383254aad5778" UNIQUE ("solarPowerPlantMaintainerId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "text" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answer" ("id" SERIAL NOT NULL, "text" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "questionId" integer, CONSTRAINT "PK_9232db17b63fb1e94f97e5c224f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_notification" ("id" SERIAL NOT NULL, "content" character varying NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_eedd392bed10015330121377b6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "off_party" ("id" SERIAL NOT NULL, "dateAndTime" TIMESTAMP NOT NULL, "address" character varying NOT NULL, "lat" double precision, "lng" double precision, "venue" character varying NOT NULL, "access" character varying NOT NULL, "price" integer NOT NULL, "form" character varying NOT NULL, "belongings" character varying NOT NULL, "clothing" character varying NOT NULL, "precautions" character varying NOT NULL, "cacellationRules" character varying NOT NULL, "content" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "creatorId" integer, CONSTRAINT "PK_46af479889a8e9fedf8948005b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating" ("id" SERIAL NOT NULL, "rating" integer NOT NULL, "comment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "evaluatorId" integer, "evaluateeId" integer, CONSTRAINT "PK_ecda8ad32645327e4765b43649e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seminar" ("id" SERIAL NOT NULL, "dateAndTime" TIMESTAMP NOT NULL, "address" character varying NOT NULL, "lat" double precision, "lng" double precision, "venue" character varying NOT NULL, "access" character varying NOT NULL, "price" integer NOT NULL, "form" character varying NOT NULL, "belongings" character varying NOT NULL, "clothing" character varying NOT NULL, "precautions" character varying NOT NULL, "cacellationRules" character varying NOT NULL, "content" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "creatorId" integer, CONSTRAINT "PK_73dcbc986401c772630a6c5d552" PRIMARY KEY ("id"))`);
        await queryRunner.query(`-- CREATE TABLE "bank_details" ("id" SERIAL NOT NULL, "bankName" character varying NOT NULL, "branchName" character varying NOT NULL, "depositItem" character varying NOT NULL, "accountNumber" integer, "accountHolderKanji" character varying NOT NULL, "accountHolderHiragana" character varying NOT NULL, "userId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),  PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "region" ADD CONSTRAINT "FK_3476e46cf3992df1ce6bd32a913" FOREIGN KEY ("areaId") REFERENCES "area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "FK_a702dde63cef536819298d776b5" FOREIGN KEY ("regionId") REFERENCES "region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" ADD CONSTRAINT "FK_6f4b3057461b2ce984fdfe15ac2" FOREIGN KEY ("solarPowerPlantOwnerId") REFERENCES "solar_power_plant_owner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" ADD CONSTRAINT "FK_5dff681247a97796e6d34bb3bb7" FOREIGN KEY ("officialSolarPowerPlantOwnerId") REFERENCES "solar_power_plant_owner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" ADD CONSTRAINT "FK_924ce027250086b6aae8491a198" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" ADD CONSTRAINT "FK_234fa83989f7046fa265cefa829" FOREIGN KEY ("regionId") REFERENCES "region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_800dbac1b41b16b232fbf42f100" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_40241560dca5f4152197cc6ad7a" FOREIGN KEY ("solarPowerPlantMaintainerId") REFERENCES "solar_power_plant_maintainer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" ADD CONSTRAINT "FK_c30515be97af9ab6316b00ddeb1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" ADD CONSTRAINT "FK_70f3e9132610b21f58018b1d1c2" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_file_info" ADD CONSTRAINT "FK_db6ee5fb2e78f1b3ef77a5fef70" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_992fed01103e3421dc0c795b6c5" FOREIGN KEY ("solarPowerPlantId") REFERENCES "solar_power_plant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_a88f7852581aa0af4755862b547" FOREIGN KEY ("approvedApplicantId") REFERENCES "solar_power_plant_maintainer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_jobs" ADD CONSTRAINT "FK_bc4b1f659882cd4c737f02f6beb" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_jobs" ADD CONSTRAINT "FK_5e5d62a03dd2ead1341daa9d4ff" FOREIGN KEY ("solarPowerPlantMaintainerId") REFERENCES "solar_power_plant_maintainer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant_maintainer" ADD CONSTRAINT "FK_a84328fcf8e3e5f5885d164116c" FOREIGN KEY ("representativeId") REFERENCES "representative"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_transaction" ADD CONSTRAINT "FK_1422cc85c1642eed91e947cf877" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_5fdbbcb32afcea663c2bea2954f" FOREIGN KEY ("channelId") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_96d3ca090d4097b57746349736c" FOREIGN KEY ("uploadedFileId") REFERENCES "file_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channels_members" ADD CONSTRAINT "FK_88face098dddc62072f89abe4c6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channels_members" ADD CONSTRAINT "FK_3f684fa3eb0fed2f13583c1d12a" FOREIGN KEY ("channelId") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c4bfb1f8b58fe276fce02f1d551" FOREIGN KEY ("solarPowerPlantOwnerId") REFERENCES "solar_power_plant_owner"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_21c478baa4640383254aad57783" FOREIGN KEY ("solarPowerPlantMaintainerId") REFERENCES "solar_power_plant_maintainer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_80f29cc01d0bd1644e389cc13be" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer" ADD CONSTRAINT "FK_5a26907efcd78a856c8af5829e6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer" ADD CONSTRAINT "FK_a4013f10cd6924793fbd5f0d637" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_notification" ADD CONSTRAINT "FK_d3ba14f5b86336519297f943764" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "off_party" ADD CONSTRAINT "FK_d7cc0d6d99e6d0a01161bfd2054" FOREIGN KEY ("creatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_c2f458603a5c6b79a9f79f513dc" FOREIGN KEY ("evaluatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_2b0c9bf747edbfd6b6693c76a0c" FOREIGN KEY ("evaluateeId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seminar" ADD CONSTRAINT "FK_97c7262f35c815a01b452a1c687" FOREIGN KEY ("creatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "seminar" DROP CONSTRAINT "FK_97c7262f35c815a01b452a1c687"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_2b0c9bf747edbfd6b6693c76a0c"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_c2f458603a5c6b79a9f79f513dc"`);
        await queryRunner.query(`ALTER TABLE "off_party" DROP CONSTRAINT "FK_d7cc0d6d99e6d0a01161bfd2054"`);
        await queryRunner.query(`ALTER TABLE "app_notification" DROP CONSTRAINT "FK_d3ba14f5b86336519297f943764"`);
        await queryRunner.query(`ALTER TABLE "answer" DROP CONSTRAINT "FK_a4013f10cd6924793fbd5f0d637"`);
        await queryRunner.query(`ALTER TABLE "answer" DROP CONSTRAINT "FK_5a26907efcd78a856c8af5829e6"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_80f29cc01d0bd1644e389cc13be"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_21c478baa4640383254aad57783"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c4bfb1f8b58fe276fce02f1d551"`);
        await queryRunner.query(`ALTER TABLE "channels_members" DROP CONSTRAINT "FK_3f684fa3eb0fed2f13583c1d12a"`);
        await queryRunner.query(`ALTER TABLE "channels_members" DROP CONSTRAINT "FK_88face098dddc62072f89abe4c6"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_96d3ca090d4097b57746349736c"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_5fdbbcb32afcea663c2bea2954f"`);
        await queryRunner.query(`ALTER TABLE "user_transaction" DROP CONSTRAINT "FK_1422cc85c1642eed91e947cf877"`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant_maintainer" DROP CONSTRAINT "FK_a84328fcf8e3e5f5885d164116c"`);
        await queryRunner.query(`ALTER TABLE "favorite_jobs" DROP CONSTRAINT "FK_5e5d62a03dd2ead1341daa9d4ff"`);
        await queryRunner.query(`ALTER TABLE "favorite_jobs" DROP CONSTRAINT "FK_bc4b1f659882cd4c737f02f6beb"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_a88f7852581aa0af4755862b547"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_992fed01103e3421dc0c795b6c5"`);
        await queryRunner.query(`ALTER TABLE "job_file_info" DROP CONSTRAINT "FK_db6ee5fb2e78f1b3ef77a5fef70"`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" DROP CONSTRAINT "FK_70f3e9132610b21f58018b1d1c2"`);
        await queryRunner.query(`ALTER TABLE "payment_transaction" DROP CONSTRAINT "FK_c30515be97af9ab6316b00ddeb1"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_40241560dca5f4152197cc6ad7a"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_800dbac1b41b16b232fbf42f100"`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" DROP CONSTRAINT "FK_234fa83989f7046fa265cefa829"`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" DROP CONSTRAINT "FK_924ce027250086b6aae8491a198"`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" DROP CONSTRAINT "FK_5dff681247a97796e6d34bb3bb7"`);
        await queryRunner.query(`ALTER TABLE "solar_power_plant" DROP CONSTRAINT "FK_6f4b3057461b2ce984fdfe15ac2"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "FK_a702dde63cef536819298d776b5"`);
        await queryRunner.query(`ALTER TABLE "region" DROP CONSTRAINT "FK_3476e46cf3992df1ce6bd32a913"`);
        await queryRunner.query(`DROP TABLE "seminar"`);
        await queryRunner.query(`DROP TABLE "rating"`);
        await queryRunner.query(`DROP TABLE "off_party"`);
        await queryRunner.query(`DROP TABLE "app_notification"`);
        await queryRunner.query(`DROP TABLE "answer"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_accounttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "channels_members"`);
        await queryRunner.query(`DROP TABLE "channel"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "file_info"`);
        await queryRunner.query(`DROP TABLE "user_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."user_transaction_status_enum"`);
        await queryRunner.query(`DROP TABLE "solar_power_plant_maintainer"`);
        await queryRunner.query(`DROP TABLE "representative"`);
        await queryRunner.query(`DROP TABLE "favorite_jobs"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TYPE "public"."job_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_file_info"`);
        await queryRunner.query(`DROP TABLE "payment_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transaction_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_applications"`);
        await queryRunner.query(`DROP TABLE "solar_power_plant"`);
        await queryRunner.query(`DROP TABLE "solar_power_plant_owner"`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP TABLE "region"`);
        await queryRunner.query(`DROP TABLE "area"`);
    }

}
